#spring:
#  http:
#    encoding:
#      charset: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Hubu88661126--
    #url: jdbc:mysql://192.168.30.113/sell?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://39.108.156.55/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    #host: 192.168.30.113
    host: 39.108.156.55
    port: 6379
server:
  servlet:
    context-path: /drool