package rules;
import edu.hubu.entity.Order

rule "zero"
    no-loop true
    lock-on-active true
    salience 1
    when
        $s : Order(amount <= 100)
    then
        $s.setScore($s.getScore()+0);
        update($s)
end

rule "add100"
    no-loop true
    lock-on-active true
    salience 1
    when
        $s : Order(amount > 100 && amount <= 500)
    then
        $s.setScore($s.getScore()+100);
        update($s)
end


rule "add500"
    no-loop true
    lock-on-active true
    salience 1
    when
        $s : Order(amount > 500 && amount <= 1000)
    then
        $s.setScore($s.getScore()+500);
        update($s)
end

rule "add1000"
    no-loop true
    lock-on-active true
    salience 1
    when
        $s : Order(amount > 1000)
    then
        $s.setScore($s.getScore()+500);
        update($s)
end